#!/bin/sh
mkdir -p vendor/
cd vendor/
if [ -d "small-rxjs" ]; then
	git -C small-rxjs fetch -tap
	git -C small-rxjs checkout 1.0.1
else
	git clone -b 1.0.1 https://github.com/thiagofleal/small-rxjs small-rxjs
fi
cd ..