#!/bin/bash
mkdir -p vendor/
cd vendor/
git clone https://github.com/thiagofleal/small-rxjs small-rxjs
cd small-rxjs
git fetch https://github.com/thiagofleal/small-rxjs && git checkout master
git pull https://github.com/thiagofleal/small-rxjs master
git checkout de6d4bf66aa231768cd6a026dff79ccc841eaa6d
cd ..